#!/usr/bin/env python3
"""
Regenerates the app's UI icons (app/src/main/res/drawable/ic_*.xml) from
Material Symbols — Rounded, weight 400, outlined (fill 0), 24 dp — so every
icon in the app is drawn in one modern style.

    npm pack @material-symbols/svg-400@0.47.5 && tar xzf material-symbols-svg-400-*.tgz
    python3 art/material-symbols/generate.py package/rounded

Material Symbols are Apache-2.0 (Google). To add an icon: add a row to ICONS
(drawable name → symbol name), rerun, and use R.drawable.<name>.
"""
import pathlib
import re
import sys

SYMBOLS_VERSION = "0.47.5"

# drawable name -> (Material Symbols name, mirrors in RTL)
ICONS = {
    # navigation / chrome
    "ic_arrow_back": ("arrow_back", True),
    "ic_arrow_forward": ("arrow_forward", True),
    "ic_more_vert": ("more_vert", False),
    "ic_expand_more": ("keyboard_arrow_down", False),
    "ic_close": ("close", False),
    "ic_search": ("search", False),
    # converter top bar + drawer
    "ic_timeline": ("show_chart", False),
    "ic_cart": ("shopping_cart", False),
    "ic_split": ("call_split", False),
    "ic_table": ("table_chart", False),
    "ic_history": ("history", False),
    "ic_refresh": ("refresh", False),
    "ic_share": ("share", False),
    "ic_data_provider": ("account_balance", False),
    "ic_fee": ("percent", False),
    "ic_settings": ("settings", False),
    # converter / cart content
    "ic_swap_horiz": ("swap_horiz", False),
    "ic_backspace": ("backspace", True),
    "ic_add": ("add", False),
    "ic_remove": ("remove", False),
    "ic_delete": ("delete", False),
    "ic_edit": ("edit", False),
    "ic_drag_handle": ("drag_handle", False),
    "ic_favorite": ("favorite", False),
    "ic_favorite_filled": ("favorite-fill", False),
    "ic_cloud_off": ("cloud_off", False),
    "ic_sync_problem": ("sync_problem", False),
    "ic_visibility": ("visibility", False),
    "ic_visibility_off": ("visibility_off", False),
    # cart menu
    "ic_save": ("save", False),
    "ic_save_as": ("save_as", False),
    "ic_folder_open": ("folder_open", False),
    "ic_upload": ("upload", False),
    "ic_download": ("download", False),
    # timeline
    "ic_tune": ("tune", False),
    "ic_trending_up": ("trending_up", False),
    "ic_trending_down": ("trending_down", False),
    # settings
    "ic_keyboard_extended": ("calculate", False),
    "ic_numbers": ("decimal_increase", False),
    "ic_backup": ("backup", False),
    "ic_key": ("key", False),
    "ic_info": ("info", False),
    "ic_schedule": ("schedule", False),
    "ic_theme": ("contrast", False),
    "ic_palette": ("palette", False),
    "ic_language": ("language", False),
    "ic_event": ("event", False),
    "ic_vibration": ("mobile_vibrate", False),
    "ic_conversion_preview": ("preview", False),
    "ic_gavel": ("gavel", False),
    "ic_code": ("code", False),
    "ic_rate": ("star", False),
    "ic_changelog": ("update", False),
    "ic_tag": ("tag", False),
}

# Launcher-shortcut glyphs: drawable name -> symbol, drawn in ink inside an
# adaptive icon's 108 dp canvas (the glyph fills the middle 44 dp, well inside
# the 72 dp safe zone). Wrapped by res/drawable/shortcut_*.xml.
SHORTCUT_GLYPHS = {
    "shortcut_cart_foreground": "shopping_cart",
    "shortcut_pair_foreground": "currency_exchange",
}
SHORTCUT_CANVAS = 108
SHORTCUT_GLYPH = 44

SHORTCUT_TEMPLATE = """<?xml version="1.0" encoding="utf-8"?>
<!-- Material Symbols Rounded "{symbol}" (weight 400), Apache-2.0, as a launcher-
     shortcut foreground. Generated by art/material-symbols/generate.py. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{canvas}dp"
    android:height="{canvas}dp"
    android:viewportWidth="{canvas}"
    android:viewportHeight="{canvas}">
    <group
        android:translateX="{offset}"
        android:translateY="{offset}"
        android:scaleX="{scale}"
        android:scaleY="{scale}">
        <group android:translateY="960">
            <path
                android:fillColor="@color/billGreenInk"
                android:pathData="{path}" />
        </group>
    </group>
</vector>
"""

TEMPLATE = """<?xml version="1.0" encoding="utf-8"?>
<!-- Material Symbols Rounded "{symbol}" (weight 400, fill {fill}), Apache-2.0.
     Generated by art/material-symbols/generate.py; edit that, not this. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"{mirror}
    android:tint="?attr/colorControlNormal"
    android:viewportWidth="960"
    android:viewportHeight="960">
    <group android:translateY="960">
        <path
            android:fillColor="@android:color/white"
            android:pathData="{path}" />
    </group>
</vector>
"""


def read_path(src: pathlib.Path, symbol: str) -> str:
    svg = (src / f"{symbol}.svg").read_text()
    paths = re.findall(r'<path d="([^"]+)"', svg)
    if len(paths) != 1 or 'viewBox="0 -960 960 960"' not in svg:
        sys.exit(f"{symbol}: unexpected SVG shape")
    return paths[0]


def main(src: pathlib.Path, out: pathlib.Path) -> None:
    for name, symbol in SHORTCUT_GLYPHS.items():
        (out / f"{name}.xml").write_text(
            SHORTCUT_TEMPLATE.format(
                symbol=symbol,
                canvas=SHORTCUT_CANVAS,
                offset=(SHORTCUT_CANVAS - SHORTCUT_GLYPH) / 2,
                scale=round(SHORTCUT_GLYPH / 960, 6),
                path=read_path(src, symbol),
            )
        )
    for name, (symbol, mirrors) in ICONS.items():
        paths = [read_path(src, symbol)]
        (out / f"{name}.xml").write_text(
            TEMPLATE.format(
                symbol=symbol.removesuffix("-fill"),
                fill=1 if symbol.endswith("-fill") else 0,
                mirror='\n    android:autoMirrored="true"' if mirrors else "",
                path=paths[0],
            )
        )
    print(f"wrote {len(ICONS)} icons (Material Symbols {SYMBOLS_VERSION}) to {out}")


if __name__ == "__main__":
    repo = pathlib.Path(__file__).resolve().parents[2]
    main(pathlib.Path(sys.argv[1]), repo / "app/src/main/res/drawable")
